apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 10Gi  # Adjust size according to your needs
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mongodb  # Ensure this matches your actual GCE PD name
    fsType: ext4

